import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  keywords: "about, company, ai, saas",
  twitter: {
    card: "summary_large_image",
    title: "ABout us Twitter"
  }
};

export default function About(){
    return <h1>hello</h1>;
}