import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// GLOBAL Metadata - for server component
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  keywords: "about, company, ai, saas",
  twitter: {
    card: "summary_large_image",
    title: "ABout us Twitter"
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div>
          {""}
            <Link href={"/"}>Home</Link>
            <Link href={"/about"}>About</Link>
            <Link href={"/contact"}>Contact</Link>
            <Link href={"/users"}>Users</Link>
        </div>
        {children}
      </body>
    </html>
  );
}
